# TODO re-enable coverage checking for the following cmd files
ignore:
  - "cloud/*/types"
  - "/cmd/create*"
  - "/cmd/delete*"
  - "/cmd/export*"
  - "/cmd/get*"
  - "/cmd/upgrade*"
  - "/cmd/root*"
  - "/cmd/version*"
